apiVersion: v1
kind: Template
labels:
  template: fabric8-analytics-bigquery-manifests-job
metadata:
  name: fabric8-analytics-bigquery-manifests-job
  annotations:
    description: fabric8-analytics-bigquery-manifests-job
objects:
- apiVersion: batch/v1beta1
  kind: CronJob
  metadata:
    name: fabric8-analytics-bigquery-manifests-job
    annotations:
      description: fabric8-analytics-bigquery-manifests-job
  spec:
    successfulJobsHistoryLimit: 4
    failedJobsHistoryLimit: 0
    concurrencyPolicy: "Forbid"
    schedule: "${CRON_SCHEDULE}"
    jobTemplate:
      spec:
        template:
          spec: 
            restartPolicy: Never
            containers:
            - name: f8a-bq-manifests-job
              image: "${DOCKER_REGISTRY}/${DOCKER_IMAGE}:${IMAGE_TAG}"
              env:
                - name: DEBUG
                  value: "true"
                - name: AWS_S3_ACCESS_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      key: s3-access-key-id
                      name: aws
                - name: AWS_S3_SECRET_ACCESS_KEY
                  valueFrom:
                    secretKeyRef:
                      key: s3-secret-access-key
                      name: aws
                - name: DEPLOYMENT_PREFIX
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: deployment-prefix
                - name: AWS_S3_REGION
                  valueFrom:
                    configMapKeyRef:
                      name: bayesian-config
                      key: aws-default-region
                - name: GCP_TYPE
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_type
                - name: GCP_PROJECT_ID
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_project_id
                - name: GCP_PRIVATE_KEY_ID
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_private_key_id
                - name: GCP_PRIVATE_KEY
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_private_key
                - name: GCP_CLIENT_EMAIL
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_client_email
                - name: GCP_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_client_id
                - name: GCP_AUTH_URI
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_auth_uri
                - name: GCP_TOKEN_URI
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_token_uri
                - name: GCP_AUTH_PROVIDER_X509_CERT_URL
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_auth_provider_x509_cert_url
                - name: GCP_CLIENT_X509_CERT_URL
                  valueFrom:
                    secretKeyRef:
                      name: google-cloud-key
                      key: gcp_client_x509_cert_url
              resources:
                requests:
                  cpu: ${CPU_REQUEST}
                  memory: ${MEMORY_REQUEST}
                limits:
                  cpu: ${CPU_LIMIT}
                  memory: ${MEMORY_LIMIT}
parameters:
  - description: Docker registry
    displayName: Docker registry
    required: true
    name: DOCKER_REGISTRY
    value: "quay.io"

  - description: Docker image
    displayName: Docker image
    required: true
    name: DOCKER_IMAGE
    value: "openshiftio/rhel-fabric8-analytics-f8a-bq-manifests-job"

  - description: Image tag
    displayName: Image tag
    required: true
    name: IMAGE_TAG
    value: "latest"

  - description: Schedule
    displayName: Schedule
    required: true
    name: CRON_SCHEDULE
    value: "0 0 1 */1 *"

  - description: CPU request
    displayName: CPU request
    required: true
    name: CPU_REQUEST
    value: "500m"

  - description: CPU limit
    displayName: CPU limit
    required: true
    name: CPU_LIMIT
    value: "800m"

  - description: Memory request
    displayName: Memory request
    required: true
    name: MEMORY_REQUEST
    value: "512Mi"

  - description: Memory limit
    displayName: Memory limit
    required: true
    name: MEMORY_LIMIT
    value: "1024Mi" 